print("------------------------------------------------------------------")
print("Bienvenidos a la práctica de github!")
print("Este es un ejercicio colaborativo para practicar el uso de github.")
print("------------------------------------------------------------------")
print("Vamos a agregar nuestros nombres a continuación:")
print()
print("Acá estuvo Damian Ene. Se creó el PR y fue controlado por 'pepe'.")
print("Aca estuvo bautista menghini.")
print("Acá estuvo Aldana Aranda.")

print("Matias Nicolas Cappa y lo controlo Lucas Bertone")
print("Aca estuvo Lucas Bertone")
print("En main ustedes ya aprobaron PRs con sus nombres, si hago merge con esto, ¿que pasara?")
print("Generando conflictos!!! MUEJEJE")

