
print("------------------------------------------------------------------")
print("Bienvenidos a la práctica de github!")
print("Este es un ejercicio colaborativo para practicar el uso de github.")
print("------------------------------------------------------------------")
print("Vamos a agregar nuestros nombres a continuación:")
print("Aca estuvo Lucas Bertone")
print("Acá estuvo Damian Ene. Se creó el PR y fue controlado por 'pepe'.")
print()
print("Acá estuvo Damian Ene. Se creó el PR y fue controlado por 'pepe'.")
print("Acá estuvo el Barto. Esto lo corrigió el baucha")
print("Aca estuvo bautista menghini. Se creo el PR y fue controlado por matute")
print("Acá estuvo Aldana Aranda")