
print("------------------------------------------------------------------")
print("Bienvenidos a la práctica de github!")
print("Este es un ejercicio colaborativo para practicar el uso de github.")
print("------------------------------------------------------------------")
print("Vamos a agregar nuestros nombres a continuación:")
print("Aca estuvo Lucas Bertone")
print("Acá estuvo Damian Ene. Se creó el PR y fue controlado por 'pepe'.")
print()
print("Acá estuvo Damian Ene. Se creó el PR y fue controlado por 'pepe'.")
print("Aca estuvo bautista menghini.")
print("Acá estuvo Aldana Aranda")
print("aca anduvo gianluca")
print("un dois tres, tres dois uno, todo el mundo sobre dos, raiz en daida uno.")